#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

#  create the index page
touch /var/www/html/index.html
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# create a webpage for error 404
# touch /var/www/html/404.html
# echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=Q51jCWzKVYU;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default

# code to create a webpage for 4040 and configure redirect
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
err_page="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $err_page" /etc/nginx/sites-available/default

# restart the web server after updating the settings
service nginx start
sudo service nginx reload

